# Generated by Django 4.0.4 on 2022-05-15 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_publishedmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PublishedManager',
        ),
    ]
